npm test src/__tests__/requirement01
npm test src/__tests__/requirement02
npm test src/__tests__/requirement03
npm test src/__tests__/requirement04
npm test src/__tests__/requirement05
npm test src/__tests__/requirement06
npm test src/__tests__/requirement07
npm test src/__tests__/requirement08
npm test src/__tests__/requirement09
npm test src/__tests__/requirement10
npm test src/__tests__/requirement11
npm test src/__tests__/requirement13
npm test src/__tests__/requirement15
